ARG FATE_VERSION=1.6.0
FROM crossflowai/fate_base:${FATE_VERSION}-release
ENV FATE_VERSION 1.6.0
WORKDIR /
RUN mkdir /Examples
RUN pip install jupyter requests_toolbelt>=0.9.1 click>=7.1.2 poetry>=0.12 loguru>=0.5.1 && pip cache purge
COPY flow pipeline /usr/local/bin/
WORKDIR /data/projects/fate
ENV PYTHONPATH /data/projects/fate/python:/data/projects/fate/python/fate_client
CMD ["/bin/sh", "-c", "flow init -c conf/service_conf.yaml && pipeline init -c conf/pipeline_conf.yaml && jupyter notebook --ip=0.0.0.0 --port=20000 --allow-root --debug --NotebookApp.notebook_dir='/Examples' --no-browser --NotebookApp.token='' --NotebookApp.password=''"]
