ARG ZK_VERSION=3.7.0
FROM zookeeper:${ZK_VERSION}
ENV ZK_VERSION=3.7.0
#RUN chmod -R 777 $ZOO_CONF_DIR
#RUN chmod -R 777 $ZOO_DATA_DIR
#RUN chmod -R 777 $ZOO_DATA_LOG_DIR
#RUN chmod -R 777 $ZOO_LOG_DIR
RUN deluser zookeeper
ENV ZOO_VOLUME_DIR=/bitnami/zookeeper
ENV ZOO_DATA_DIR=${ZOO_VOLUME_DIR}/data
#ENV ZOO_DATA_DIR=/new_data
ENV ZOO_DATA_LOG_DIR=/new_datalog
ENV ZOO_LOG_DIR=/new_logs
RUN set -eux && \
    groupadd -r zookeeper --gid=1001 && \
    mkdir -p "$ZOO_DATA_DIR" "$ZOO_DATA_LOG_DIR" "$ZOO_LOG_DIR" && \
    useradd -r -g zookeeper --uid=1001 zookeeper && \
    chown -R zookeeper:zookeeper "/apache-zookeeper-${ZK_VERSION}-bin" "$ZOO_DATA_LOG_DIR" "$ZOO_DATA_DIR" "$ZOO_CONF_DIR" "$ZOO_LOG_DIR"
VOLUME ["$ZOO_DATA_DIR", "$ZOO_DATA_LOG_DIR", "$ZOO_LOG_DIR"]
COPY entrypoint.sh run.sh /
ENTRYPOINT ["/entrypoint.sh"]
CMD ["/run.sh"]
